### ISSUE TITLE
Add a Partnership section below the form

### ISSUE THREAD

**Issue by stbensonimoh** [pinafrica/awlo-ga-registration-frontend#11]
A new section below the form should be created with the partners' logos and caption like so:
![PINAFRICA Logo](https://pinafrica.org/static/logo.svg) <br>
Technology Partner.
![stbenonimoh](https://stbensonimoh.com/wp-content/uploads/2019/03/logo.svg) <br>
Assessment Partner.

**Comment by osumgbachiamaka** [comment]
@stbensonimoh I don't know what this will look like.
Do you have any picture in mind.

**Comment by stbensonimoh** [comment]
I will work on this myself.
